services:
  quizconnectserver:
    build:
      context: .
      dockerfile: Dockerfile
      environment:
      - APP_UID=1000
    ports:
      - "8080:8080"
    volumes:
      - ./Server/.env:/app/.env
    restart: unless-stopped